### ISSUE TITLE
Searchbar color change not in sync w/ dark mode transition

### ISSUE THREAD

**Issue by win21H2** [Syknapse/Contribute-To-This-Project#1471]
When switching to dark mode, there is no animation change for the searchbar which makes it look weird when it is transitioning

**Comment by win21H2** [comment]
done 'n' dusted. Added an animation line to the searchbar

**Comment by ataljka** [comment]
@

> When switching to dark mode, there is no animation change for the searchbar which makes it look weird when it is transitioning
