### ISSUE TITLE
My card not showing up.

### ISSUE THREAD

**Issue by ALCUNOO** [Syknapse/Contribute-To-This-Project#1642]
Hi!

I recently added my card and [my PR](https://github.com/Syknapse/Contribute-To-This-Project/pull/1641) was approved. I checked the website, and I don't see my card...? I'm an absolute newbie to this GitHub contributing/etc stuff so I dunno what I did wrong. Help much appreciated.

**Comment by Preet-Sojitra** [comment]
We haven't merged your PR yet. Once we will merge it you can view it on website.

**Comment by Preet-Sojitra** [comment]
Hey @ALCUNOO there are few changes which has to be made. I have mentioned those changes in [your PR ](#1641). Kindly make those changes. If you need any help feel free to ask it here. I would be happy to help you.
