### ISSUE TITLE
Add a PageUp Scroll Button

### ISSUE THREAD

**Issue by mgjain9871** [Syknapse/Contribute-To-This-Project#1804]
Under this issue, i will be creating a scroll up button.
Please assign me this issue under hactoberfest
@Syknapse

**Comment by deepesh0706** [comment]
Hi, I can help you to add the PageUp Scroll Button please assign me this issue

**Comment by win21H2** [comment]
Hello,
Because we have a scroll-to-top button implemented and a few other issues talking about it, I will close this issue!

Thanks,
win21H2
324Hz
