### ISSUE TITLE
Missing text in French translation

### ISSUE THREAD

**Issue by christopheMeudec** [Syknapse/Contribute-To-This-Project#1862]
There are missing paragraphs in [the French translation](https://github.com/Syknapse/Contribute-To-This-Project/blob/master/translations/README/FRENCH.md): (Step 3, Step4 and Step 5)

![image](https://user-images.githubusercontent.com/22070704/194054759-0565d0a7-53eb-494e-978c-2c28bcc5b8fc.png)

I can fix it for hactoberfest

**Comment by TenTraicion** [comment]
@christopheMeudec waiting for your PR. Thanks!
