### ISSUE TITLE
Remove JQuery from the project

### ISSUE THREAD

**Issue by Syknapse** [Syknapse/Contribute-To-This-Project#1899]
Several features in [script.js](../blob/master/assets/script.js) have been created with JQuery. We can migrate those to vanilla JS to make the script all coherent and this will allow us to remove the JQuery CDN from the project. Jquery has been there for us for a long time but it is time to retire it if it is not needed, and it's possible that we can replace the features with pure JS without much trouble.

**Comment by PruthviGBhat** [comment]
Hi @Syknapse , I'm beginner to open source, Is anyone working on the issue? if not Can I?

**Comment by Syknapse** [comment]
Of course, if you feel like it you can. That would be great

**Comment by Preet-Sojitra** [comment]
> Hi @Syknapse , I'm beginner to open source, Is anyone working on the issue? if not Can I?

Are you working on this? If yes I will assign this issue to you

**Comment by PruthviGBhat** [comment]
Yes I'm working on the issue

**Comment by PruthviGBhat** [comment]
I searched about the failed checks but I didn't get it, Can you please guide me
