### ISSUE TITLE
Font color in search bar need for lighter color

### ISSUE THREAD

**Issue by ImanHasan** [Syknapse/Contribute-To-This-Project#2071]

**Comment by ImanHasan** [comment]
I want to solve this please assign this issue to me.

**Comment by TenTraicion** [comment]
@ImanHasan, sorry about that. you should've created a PR and mentioned this issue as early as possible. This has done by another, you can create a PR also with better color/font idea and mention this issue as well
If yours is better then we will merge it and close this issue as well. Thanks!
