### ISSUE TITLE
need design improvment in scroll up button

### ISSUE THREAD

**Issue by ImanHasan** [Syknapse/Contribute-To-This-Project#2095]

**Comment by TenTraicion** [comment]
Sure, you can open a PR. Thanks for the contribution.

**Comment by ZubairImtiaz3** [comment]
@TenTraicion i have done working on this issue. Please assign me this issue. I'm opening a PR too.

**Comment by TenTraicion** [comment]
@ImanHasan, I will close this PR for no response and we already have a sufficient PR. but if you think you can improve this a bit better, make your PR and mention this issue. We will wait for 72 hours.

@ZubairImtiaz3, sorry for the wait but we've already assigned this issue to @ImanHasan and we will wait 72 hours from now for his response. if he failed to open a pr, your PR is good to go. Thanks!

**Comment by ImanHasan** [comment]
> Sure, you can open a PR. Thanks for the contribution.

Sure Thank you
