### ISSUE TITLE
Updation of page

### ISSUE THREAD

**Issue by RGupta-design** [Syknapse/Contribute-To-This-Project#2234]
Upon searching a card by name, the card appears with first letter of the card(name of card maker) in lowercase. Reverts to correct case after refreshing the page.

**Comment by Abinash-bit** [comment]
@RGupta-design I am intrested in solving this issue please guide me.

**Comment by TenTraicion** [comment]
> @RGupta-design I am intrested in solving this issue please guide me.

 @Abinash-bit, sure. waiting for your changes..! make sure to mention this issue on your commit. Thanks.

**Comment by sdhrrr** [comment]
Heyy! I am new to contribute to open source.  Could you please assign this issue to me.

**Comment by sameer-555** [comment]
Hey everyone, I'm also new to open source contribution, can you please assign me this issue

**Comment by DennisGH22** [comment]
Hi Guys,

I resolved the issue a couple of weeks ago, but I see it is not merged into the repo only approved by @TenTraicion?

**Comment by TenTraicion** [comment]
@DennisGH22, hey there. your pr was awaiting approval from the repo owner thats why it wasn't merged. Sorry for being late, Happy Coding!

**Comment by DennisGH22** [comment]
@TenTraicion, thank you.
