### ISSUE TITLE
Change Font Awesome `fa` icon prefix to `fab`

### ISSUE THREAD

**Issue by Syknapse** [Syknapse/Contribute-To-This-Project#226]
Many of the Twitter (and other social networks) icons on the page are broken and not showing correctly.
It seems the recent upgrade to the new Font Awesome library has broken many of those because of change in the prefix used for the icons from  `fa` icon prefix to `fab`. For example `fa fa-twitter` becomes `fab fa-twitter`. This needs to be investigated and if it is the case change all the wrong prefixes for the correct one including in the template.

**Comment by Azmaeus** [comment]
@Syknapse you mentioned in #216 I could "claim" this issue and resolve it. I see a "New Issue" button, but no "Claim" button, how do I go about claiming an issue?

**Comment by Azmaeus** [comment]
Fixed in PR #228

**Comment by Syknapse** [comment]
I see you already resolved the doubt you had. That was my idea, you just took it upon yourself to fix it, thanks a lot, that was a really useful collaboration 👍
