### ISSUE TITLE
Review and Fix Markdown on README.md

### ISSUE THREAD

**Issue by ArslanYM** [Syknapse/Contribute-To-This-Project#2422]
Increasingt the font size will enhance the readability of the readme
: 
Currently it looks like this and its hard to distinguish 
![rerad](https://user-images.githubusercontent.com/104521101/226099292-a5e448ad-a0d3-48ef-8e9d-693a6f2f5204.png)

If this issue is valid , Please assign me this issue!

**Comment by TenTraicion** [comment]
@ArslanYM, Thanks for your concern and we would love to improve the readability of our documentation. But we are against the issue of languages except Markdown provided by GitHub. If you can edit the readme with only the GitHub Markdown, you are welcome to make a PR. mention me if you are ready, I will assign you this issue. Thanks!

You are also welcome to join our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) and be a part of our community.

**Comment by Aremu-olusegun** [comment]
is this issue still available?

**Comment by ArslanYM** [comment]
> wn provided by GitHub. If you can edit the readme with only the GitHub Markdown, you are welcome to make a PR

Okay assign me , I will start my work

**Comment by ArslanYM** [comment]
Thankyou for assigning me , I have started working on it

**Comment by Manoj0718** [comment]
is this issue still open ?

**Comment by TenTraicion** [comment]
Note:
This Issue Branch has been moved to: `rebase-readme `
so any fix regarding this should be pushed in to that branch.

The branch will be merged with main and deleted after below task is completed.

- [ ] Fix Markdown in main README.md
- [ ] Fix Markdown on Language Readme
- [ ] Fix Markdown on Guides
- [ ] minor/major enhancements of Markdown
- [ ] recheck and finishing up
- [ ] merge & deploy

**Comment by Devin-The-Dev** [comment]
I'm not finding anything that needs fixing. Has this been issue resolved?

**Comment by TenTraicion** [comment]
> I'm not finding anything that needs fixing. Has this been issue resolved?

this issue will be resolved within a week . We the maintainers are working on it rn. any fix-pr is welcome on `rebase-readme` branch. Thanks!
