### ISSUE TITLE
Improve hindi readme

### ISSUE THREAD

**Issue by akkshayTandon** [Syknapse/Contribute-To-This-Project#2429]
# Issue

* improve HINDI.md
  * links are not working and images are not showing
# Steps

* fork the repository and clone it(if working locally)
* find the file [here](https://github.com/Syknapse/Contribute-To-This-Project/blob/master/translations/README/HINDI.md) 
* make changes in you own branch and open a pull request
* code will be reviewed and merged after resolving conflicts, if any.

**Comment by DhruvMishra1826** [comment]
@Syknapse @akkshayTandon i have updated it. please review the PR.
