### ISSUE TITLE
Review and Fix Markdown on Project Documentations

### ISSUE THREAD

**Issue by TenTraicion** [Syknapse/Contribute-To-This-Project#2548]
It's a long time since we've been maintaining this project and thousands were being helped by this till now. It's now time to focus and upgrade/fix some facilities like project documentation (readme, translation, guides etc) to fix or add/remove some features. I'm starting with the documentation. Github has its own markdown to write such docs but unfortunately we used to many other syntax (html tags, js, external bbcode that aren't supported), so we need to replace them with pure [GitHub Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax). Here is the List for this issue:

- [x] Fix Markdown in main README.md
- [x] Fix Markdown on Language Readme
- [x] Fix Markdown on Guides
- [x] minor/major enhancements of Markdown
- [x] recheck and finishing up
- [x] merge & deploy

anyone willing to help is welcome to work on [`rebase-readme`](https://github.com/Syknapse/Contribute-To-This-Project/tree/rebase-readme) branch of this project. So make sure you choose [`rebase-readme`](https://github.com/Syknapse/Contribute-To-This-Project/tree/rebase-readme) branch while opening a PR regarding this or pushing updates. The [Community Discussion](https://github.com/Syknapse/Contribute-To-This-Project/discussions) is open and you can also join our [Discord Server](https://discord.com/invite/D2e8QnyXNY) so we can discuss there too. 

- A PR regarding this issue is already open: #2489 

-Regards
TenTraicion

**Comment by shivam200446** [comment]
hey, I want to contribute to this issue. please assign
