### ISSUE TITLE
img error 

### ISSUE THREAD

**Issue by GAURAV-DEEP01** [Syknapse/Contribute-To-This-Project#2685]
Images are broken(if thats the term for it) and are not loading

**Comment by TenTraicion** [comment]
@GAURAV-DEEP01, Thanks for reaching out. can you provide some example?

**Comment by GAURAV-DEEP01** [comment]
okay  i think you fixed it :)

**Comment by TenTraicion** [comment]
closing: assuming the issue has been fixed!
