### ISSUE TITLE
terminal_tutorial.md is very similar to README, but outdated

### ISSUE THREAD

**Issue by dmytrovoytko** [Syknapse/Contribute-To-This-Project#2828]
Hi!
As I recently translated README to Ukrainian, I also plan to translate terminal_tutorial.
And I see that it's based on older version of README.

For example, the order of sections like introduction and steps. 
it's different even in small details:
#### Step 1: Fork this repository
vs 
#### Step 1 Fork this repository

I think it should be updated before I proceed with translation. 
I could do this update. Any plans to change the content there?

**Comment by TenTraicion** [comment]
@dmytrovoytko, thanks for your recent contribution and pointing that out. I was going to open issues regarding terminal and maintainer guide too, just like our main README. well if you can update it, you are more than welcome. 
point to be noted: we won't allow anything except githubs own markdown syntax, like html tags and other markdown/bbcode syntax etc. 

you can join us on our [Discord Server: https://discord.gg/tWkvS4ueVF](https://discord.gg/tWkvS4ueVF) for faster response. and Thanks again. i am assigning this issue to you.

**Comment by TenTraicion** [comment]
I guess, the issue has been dealt with : #2841 
so Closing this one.
