### ISSUE TITLE
I would like to translate into Swahili!

### ISSUE THREAD

**Issue by Njoxpy** [Syknapse/Contribute-To-This-Project#2915]
Swahili Translation

**Comment by ascodeasice** [comment]
Hi, translations are welcomed, you can follow the tutorial in `/translations/README.md`, then translate the files, and open a PR.
We (the maintainers) will then review your PR and merge it or request changes.

Look forward to your contribution!

**Comment by TenTraicion** [comment]
Note:>> Be sure to tag this Issue in your PR

**Comment by Njoxpy** [comment]
> Note:>> Be sure to tag this Issue in your PR

Ok!

**Comment by Njoxpy** [comment]
> Note:>> Be sure to tag this Issue in your PR

I wanted to personally inform you that I have successfully completed the translation of our project's README file. 
However, I want to inform you that I am currently experiencing an issue with image loading in the translated README.
any help?

**Comment by TenTraicion** [comment]
@nzaih1999, Need help here.. 
kindly handle this isseus and PR related to swahili translation. Just ping me after merging. Thanks!

**Comment by nzaih1999** [comment]
@TenTraicion I have actually reviewed the PR and it's actually ready for merge

**Comment by nzaih1999** [comment]
@Njoxpy there is already a translation ongoing in #2928

**Comment by Njoxpy** [comment]
Ok!

**Comment by nzaih1999** [comment]
You can still look for an issue that you think you can contribute to. We are always looking for contributions! Thank you!
