### ISSUE TITLE
Improvement of Main README translation - SWAHILI

### ISSUE THREAD

**Issue by MugoBrian** [Syknapse/Contribute-To-This-Project#3017]
The Swahili translation might need some format improvements, typo and grammar corrections and improvement translation to Swahili.

**Comment by fvaysh** [comment]
Heya, I have processed the Swahili translation, and modified, improved the clarity of this. I am submitting a PR of the Swahili ReadME which I worked on part by part as you wished, hope you check and merge it :)

**Comment by kamranzafar4343** [comment]
is there any thing i can contribute to?

**Comment by TenTraicion** [comment]
anyone who wants to work on it, make a pr, mention this issue and mention any of us contributors in your pr. it will be on First come First serve basis. make sure to follow proper rules mentioned in: #2826
