### ISSUE TITLE
[UI improvement]: User cards needs styling

### ISSUE THREAD

**Issue by biswabaibhab007** [Syknapse/Contribute-To-This-Project#3180]
The user cards needs improved styling be it the padding, fonts or even the color palette.

**Comment by biswabaibhab007** [comment]
@TenTraicion I can start working on it if you can assign this to me.

**Comment by win21H2** [comment]
This issue linked w/ #3182?

**Comment by biswabaibhab007** [comment]
Not really but I also thought of doing the same, nevermind I'll close this PR
