### ISSUE TITLE
Update the CICD pipeline

### ISSUE THREAD

**Issue by ascodeasice** [Syknapse/Contribute-To-This-Project#3195]
Maintainer here,
The CICD pipeline might be deprecated, if you have any experience with github action/ CICD, please check our github action, and see if it meets our need:

>  The idea was to create a process that automatically applies our Prettier formatting when a user commits (or pushes or starts a PR). The idea is that the process is invisible to the contributor and they don't have to do anything. Prettier formats the code correctly when it's pushed so it always stays in the right format, and if there is a formatting error the maintainers can clearly see it before merging and fix it. That's the theory.  In practice when we implemented it we found that since the PRs are coming from a cloned repo the CI setup was not working.
... And right now I can't tell you if the CI flow showing up in GitHub reflects a real test or it's just not working at all. 

You can comment under this issue about whether the CI is working or how to achieve our goal, thanks.

**Comment by apurvagurme** [comment]
Hi @ascodeasice, I could see branches: [master] which restricts the workflow to run only when the code changes are made in master branch. I think this may be causing the issue, because we usually make changes in separate branch and raise a PR.

**Comment by ascodeasice** [comment]
Hi, the `master` branch in yaml includes PR request, so the problem wasn't there, it was the problem in the `checkout action`. Thank you for your help though. The problem is solved for now, so I'm closing this issue
