### ISSUE TITLE
Image update required in README file

### ISSUE THREAD

**Issue by tmsagarofficial** [Syknapse/Contribute-To-This-Project#3199]
I would like to point it out that some images need update because they differ from the actual steps which we go through while doing as described in the text.

I mean to say that images are old compared to the text and hence there is a difference between them which is important to note.
Pls assign this issue to me so that i can start working on this.

**Comment by TenTraicion** [comment]
kindly elaborate or create a pr regarding this. if it's useful or important we will take that into account. Thanks!
Mention this issue in your PR or link in the development section.

> you can find us on discord for quick response.
