### ISSUE TITLE
want to updated the scroll for user attraction and colors to scroll bar and match with website theme

### ISSUE THREAD

**Issue by harshalhonde21** [Syknapse/Contribute-To-This-Project#3222]
![ss](https://github.com/Syknapse/Contribute-To-This-Project/assets/105191619/1a8f57bf-d0b6-40b8-b5d2-4d7d387c608c)
In above image the right scroll bar is basic which doesn't give nice look should updated fast to improve user interface

**Comment by harshalhonde21** [comment]
please assign this issue to me

**Comment by TenTraicion** [comment]
@harshalhonde21, sorry to inform you that we don't want any such edits. Thanks!
