### ISSUE TITLE
Update FontAwesome version

### ISSUE THREAD

**Issue by jt-pandey** [Syknapse/Contribute-To-This-Project#3237]
Version Used: v5.8.1
Latest Version: v6.4.2

I came across this issue when i tried adding the new logo of Twitter (the X logo in the index.html).
Should we change the version?

**Comment by jt-pandey** [comment]
If the version is to be upgraded, can this issue be assigned to me?

**Comment by win21H2** [comment]
Hello @jt-pandey,
If you create a local copy of the project, test it out with the updated version (to make sure everything on the website still works), and create a PR with the changes, I can review them and we can upgrade.

We just want to make sure that any changes that are made which affects any functionality of the website is tested before we deploy those upgrades.

Thanks!
