### ISSUE TITLE
Enhancement- README.md

### ISSUE THREAD

**Issue by ayushrakesh** [Syknapse/Contribute-To-This-Project#3246]
I have noticed two small enhancements. Adding hyphens in "**open-source**" at two places.

"**Make a contribution to an open source project.**"  will be "**Make a contribution to an open-source project.**"

"**make their first open source contribution.**"  will be "**make their first open-source contribution**"

I know this is not necessary but it will make the file more correct. Below I have attached the screenshot of it.

![Screenshot (77)](https://github.com/Syknapse/Contribute-To-This-Project/assets/115995339/31cf4738-fb5f-48f1-b7f9-79eae1fd2e12)

**Comment by ayushrakesh** [comment]
Please assign this issue to me.

**Comment by chinmay7016** [comment]
@ascodeasice pls assign this issue to me
