### ISSUE TITLE
ADD German Translation in Readme 

### ISSUE THREAD

**Issue by Durgesh4993** [Syknapse/Contribute-To-This-Project#3255]

**Comment by Durgesh4993** [comment]
@ascodeasice pls assign this issue to me

**Comment by rose2221** [comment]
please assign this issue to me

**Comment by parthasdey2304** [comment]
would you please assign this to me>>

**Comment by Durgesh4993** [comment]
@parthasdey2304 I am already working on this

**Comment by pikachusensei** [comment]
PLEASE ASSIGN IT TO ME

**Comment by TenTraicion** [comment]
> PLEASE ASSIGN IT TO ME

@pikachusensei  assigned

**Comment by NiGHTskY00** [comment]
please assign me this issue i want to work on it

**Comment by TenTraicion** [comment]
> please assign me this issue i want to work on it

@NiGHTskY00 assigned

**Comment by swapnilmukherjee** [comment]
Can you please assign this issue to me? I want to work on it. @TenTraicion

**Comment by TenTraicion** [comment]
@swapnilmukherjee Assigned

**Comment by Arjun-Mahanty** [comment]
@TenTraicion I am learning Git Issues and wish to solve this issue. Kindly assign.

**Comment by carlos-req** [comment]
@TenTraicion @ascodeasice Please assign me this issues

**Comment by nupurkale78** [comment]
I'm interested in working on this issue.  @TenTraicion

**Comment by carlos-req** [comment]
@TenTraicion @ascodeasice I'm interested in working on this

**Comment by kamranzafar4343** [comment]
There are alot of people who want to work on this repo!

**Comment by TenTraicion** [comment]
anyone who wants to work on it, make a pr, mention this issue and mention any of us contributors in your pr. it will be on First come First serve basis. make sure to follow proper rules mentioned in: #2826
