### ISSUE TITLE
I want to Add Docker Image in this repository 

### ISSUE THREAD

**Issue by Adidem23** [Syknapse/Contribute-To-This-Project#3308]
I want to add Docker Image for  this repository

**Comment by ascodeasice** [comment]
Explain why docker is needed, and where will the image be used for, thanks

**Comment by Adidem23** [comment]
We can image for frontend part of the code

**Comment by TenTraicion** [comment]
@Adidem23 , kindly elaborate.

**Comment by Adidem23** [comment]
You can watch this tutorial in which I have forked repo and added docker image for it : 
https://www.loom.com/share/5827fa3c738c4972a8381be2f44b157b?sid=4cb25e2a-1374-4554-ba4e-e2326bab7009 

Please review it and tell me pros and cons I will consider it . Thanks !! @TenTraicion  @ascodeasice

**Comment by ascodeasice** [comment]
Yeah, but we're not deploying this project to anywhere other than github.io. So we do not need to containerize this project for eaiser deployment. Thank you for your intention for contribution though

**Comment by Adidem23** [comment]
can I just Contribute or not then
