### ISSUE TITLE
Layout Changes

### ISSUE THREAD

**Issue by VaibhavSharma24** [Syknapse/Contribute-To-This-Project#3331]
As i went through the website I noticed that its getting really hard as the individual components who have contributed to this project are only 2 in a row which occupies a large number of unnecessary space so I want to layout them in 4 in a row which will enhance the user experience.

**Comment by TenTraicion** [comment]
![image](https://github.com/Syknapse/Contribute-To-This-Project/assets/103281314/9589f776-b547-40cc-b478-e62781ff17a1)
it's okay on my side.. 4 will be too much

**Comment by VaibhavSharma24** [comment]
Okay so should i start working on 3 with all the results : 
 1.enough gap for each card
 2.big enough font size
 3.not breaking the old design (don't change anything other than layout)
 4.Works on different size of monitors (those smaller than a laptop can have less cards)
@ascodeasice Please assign me this issue

**Comment by VaibhavSharma24** [comment]
Have made the PR for this issue #3350 Please feel free to tell me if any changes needed in the PR @ascodeasice
