### ISSUE TITLE
Update readme file

### ISSUE THREAD

**Issue by dalvishruti14** [Syknapse/Contribute-To-This-Project#3341]
Add license section in readme file.
Can I work on this?

**Comment by TenTraicion** [comment]
why should we add licence? what should we add about it?

**Comment by dalvishruti14** [comment]
Update the LICENSE section in the README file to enhance the presentation. To add a MIT logo, license badge and update the text with a cleaner format, including a hyperlink to the LICENSE file.

**Comment by win21H2** [comment]
I don't think we need to include a License section in the README as users can just click on the licence.md file. What might be good is to add in a link maybe at the bottom (@TenTraicion ?) but even that is probably not needed

**Comment by TenTraicion** [comment]
> I don't think we need to include a License section in the README as users can just click on the licence.md file. What might be good is to add in a link maybe at the bottom (@TenTraicion ?) but even that is probably not needed

as a first-time contributor, we can merge this.. but need to modify it slightly and put it at the end of the file.. (after acknowledgment or inside it...). though it's not a mandatory section. what do you say? @win21H2

**Comment by win21H2** [comment]
I'd say that's a good change to add to the bottom! You can go ahead with the edit @TenTraicion thanks!

**Comment by dalvishruti14** [comment]
@win21H2 @TenTraicion added link to license section after acknowledgement.

**Comment by dalvishruti14** [comment]
@win21H2 @TenTraicion  added link to license file below acknowledgement section.

**Comment by win21H2** [comment]
Thanks! Will merge the PR and close this issue.
