### ISSUE TITLE
Add Norwegian translations for README.md

### ISSUE THREAD

**Issue by RubenLien** [Syknapse/Contribute-To-This-Project#3367]
I am interested in assisting with the translation of the README.md file into Norwegian.

**Comment by BaboParrot** [comment]
I think i may be able to help.

**Comment by nzaih1999** [comment]
hello @RubenLien if you think you can tackle this issue I will then assign it to you

**Comment by RubenLien** [comment]
Done with the translation, just got proofreading left. When I preview md I can see the images are not found, the path is wrong. Is that something I need to worry about or will that be fixed when I merge?

**Comment by nzaih1999** [comment]
> Done with the translation, just got proofreading left. When I preview md I can see the images are not found, the path is wrong. Is that something I need to worry about or will that be fixed when I merge?

1. have you linked them well? you should read docs about rendering images with markdown . the goal is to make you do everything on your own so as to get more experience with open source.

**Comment by RubenLien** [comment]
Understood, I'll ensure everything is handled properly.
