### ISSUE TITLE
Highlight markdown Note Setup section

### ISSUE THREAD

**Issue by guspan-tanadi** [Syknapse/Contribute-To-This-Project#3384]
Markdown support to [highlight](https://github.com/orgs/community/discussions/16925) Note in blockquote. Can highlight by displaying convenient look. These can be suitable to [README](https://github.com/Syknapse/Contribute-To-This-Project#setup-) also [Terminal Tutorial](https://github.com/Syknapse/Contribute-To-This-Project/blob/master/terminal_tutorial.md#setup-) Setup section which directly have Note to highlighted.

The preview of Note look as below.
> [!NOTE]
An example.

In other side, these markdown will cause [relative link](https://github.com/orgs/community/discussions/16925#discussioncomment-7331837) error (e.g. in README), so be cautious.

**Comment by win21H2** [comment]
Could be a nice implementaiton for notices that need to be taken in readme's. Thoughts @TenTraicion?

**Comment by TenTraicion** [comment]
#3385 MERGED
