### ISSUE TITLE
Update card creation step (step 5) in main README tutorial

### ISSUE THREAD

**Issue by codeHokage1** [Syknapse/Contribute-To-This-Project#3409]
The tutorial step for creating and copying card in the main README seems quite different from the actual step to be taken in `index.html` .

While the tutorial mentioned to find the template in the `header` section, just around the `head` tag, the actual `index.html` file doesn't even have a `header` section. 

1. This shows the instruction in the README

<img width="637" alt="Syk-Contribute-Tutorial" src="https://github.com/Syknapse/Contribute-To-This-Project/assets/105186466/946d1375-582f-462c-8f25-9b4daa28f20c">

2. And this shows the actual `index.html` file
<img width="719" alt="Syk-Contribute-Readme" src="https://github.com/Syknapse/Contribute-To-This-Project/assets/105186466/484b1f5b-da5f-44ce-b31c-0790ee6e5012">

While this tutorial is absolutely amazing, this particular step may seem confusing for some first-contributors; especially some who are not very familiar with the syntax that is present in the actual file.

I will be very glad to help update this. Currently working on it and will send a PR soon!

**Comment by ascodeasice** [comment]
Hi, thanks for the issue, the file indeed doesn't have a `header` tag.
I think you can 
1. remove text about `header`
2. add more description to help user find the template (by line number/ find certain tag..., anything you think appropriate)

Also, the `head` tag is also pretty far from the template, maybe we can also update that part

@codeHokage1 , I've assigned this issue to you

**Comment by codeHokage1** [comment]
@ascodeasice Alright! I am right on it.

**Comment by codeHokage1** [comment]
Hello @ascodeasice 
I just submitted a PR with these fixes: #3411. I hope it's more contextual and understandable.
