### ISSUE TITLE
Terminal Tutorial card template step 5

### ISSUE THREAD

**Issue by guspan-tanadi** [Syknapse/Contribute-To-This-Project#3421]
Continuing #3409 to include [/readme-only/find-card-template.png](../blob/master/readme-only/find-card-template.png) in main [Terminal Tutorial](../blob/master/terminal_tutorial.md#step-5-copy-the-card-template). These changes has intend reducing the difference between main README and Terminal Tutorial regarding step 5 section. Since these related section can be referred as identical by each other.

**Comment by ascodeasice** [comment]
Sounds great, would you like to be assigned to this issue, or let someone else update it?

**Comment by guspan-tanadi** [comment]
> Sounds great, would you like to be assigned to this issue, or let someone else update it?

Feel free to have assigned. Thanks.

**Comment by guspan-tanadi** [comment]
Thanks again for assigning. For the next will mention issue by upcoming Pull Request.
