### ISSUE TITLE
Kevin's card affecting other PR

### ISSUE THREAD

**Issue by jzandag** [Syknapse/Contribute-To-This-Project#743]
move Kevin's card below the card template

**Comment by kevin-Ash** [comment]
Do I need to move it? Or is this done by maintainer?

**Comment by ParseSnip** [comment]
Hi, can I help with this?

**Comment by Syknapse** [comment]
> Hi, can I help with this?

Check if this issue still persists. My bet is that with recent changes it has been resolved. If it's the case, we can close this issue.

**Comment by kevin-Ash** [comment]
I think it can be closed as other pull requests are being accepted

**Comment by Amritanshu02** [comment]
Hello! I would like to work upon this issue , could you suggest me where to start ?

**Comment by lax0248917** [comment]
This issue is has been resolved. Kevin's card was merged in this PR (Kev's card #722) and has been moved below the template. Closing issue. Thank you to those who were interested in participating. Hang tight as I am sure there will be other opportunities. 👍
