### ISSUE TITLE
empty contact section from a contributor's card

### ISSUE THREAD

**Issue by jromest** [Syknapse/Contribute-To-This-Project#85]
![empty-contact-card](https://user-images.githubusercontent.com/25174423/38055062-42842690-330b-11e8-92c2-d2db7e206701.PNG)
________________________________________

![empty-contact-card-inspect](https://user-images.githubusercontent.com/25174423/38055072-48ff3924-330b-11e8-8d7d-01c5eae7beed.PNG)

**Comment by Syknapse** [comment]
Thanks a lot for spotting this. There seems to be two contact sections, the empty one needs deleting. If you feel like it you can do it and submit a PR
