### ISSUE TITLE
Continuous Integration/prettier Issue  

### ISSUE THREAD

**Issue by micahweston** [Syknapse/Contribute-To-This-Project#989]
When PRs are made with CI. If the PR is not made from the forked master branch CI will not be able to find file, and not pass. 

Suggested fix for issue:

- Possible change in instructions for submitting pull request.
- Is there anything we can do to change settings for CI to make sure it can find branches of forks?
![CI issue](https://user-images.githubusercontent.com/62726812/134728441-298e91b5-9b94-46d5-83eb-160310b1c07f.jpg)
#987 
![CI issue passed](https://user-images.githubusercontent.com/62726812/134728523-96f03b68-f1b8-4451-93fc-d47bb5b93d5c.jpg)
#988

**Comment by moonbe77** [comment]
I confirm waht micahweston discovered, 
If you create a PR from master it pass the checks, 
if the PR is from the branch it does not pass.

In my opinion is makes sense to create the PR from the branch and not from master.
This way is how We usually doit in my workplace.

**Comment by win21H2** [comment]
Or we could just manually update the HTML file (which is what I did for some of the cards using `CTRL + K + F` in vscode)

**Comment by Syknapse** [comment]
Having an automated way to make sure the project consistently remains organised by prettier, especially after being forked and submitted by a contributor would be a big advantage. It is an area that would be worth investing time in to figure out how to solve and improve.

**Comment by TenTraicion** [comment]
closing the issue: the project has pre-commit prettier configuration now.
